config:
  save_model: true
  dry_run: false
  log_intervall: 10
  manual_seed: false
  seed: 1
dataset:
  rgb: false
  train: 
    root: processed-data/dsen_2_256_split/timeperiod1/train
    kwargs:
      batch_size: 16
  test:
    root: processed-data/dsen_2_256_split/timeperiod1/val
    kwargs:
        batch_size: 16
train:
  no_cuda: false
  epochs: 20
  lr: 0.001
cuda_kwargs:
    num_workers: 1
    pin_memory: true
    shuffle: true
  
  