config:
  save_model: true
  dry_run: true
  log_intervall: 5
  manual_seed: false
  seed: 1
dataset:
  rgb: false
  train: 
    root: processed-data/dsen_2_256_new_split/timeperiod1/train
    kwargs:
        batch_size: 10
        shuffle: true
  test:
    root: processed-data/dsen_2_256_new_split/timeperiod1/val
    kwargs:
        batch_size: 10
        shuffle: true
train:
  no_cuda: false
  epochs: 20
  lr: 0.001
cuda_kwargs:
    num_workers: 1
    pin_memory: true
  
  