##################################################################
### class_dic
##################################################################
#class_dic = {
# '11100': {'class_name': 'Continuous Urban Fabric (S.L. &amp;gt; 80%)','train_id': 1},
# '11210': {'class_name': 'Discontinuous Dense Urban Fabric (S.L. : 50% - 80%)','train_id': 2},
# '11220': {'class_name': 'Discontinuous Medium Density Urban Fabric (S.L. : 30% - 50%)','train_id': 3},
# '11230': {'class_name': 'Discontinuous Low Density Urban Fabric (S.L. : 10% - 30%)','train_id': 4},
# '11240': {'class_name': 'Discontinuous Very Low Density Urban Fabric (S.L. &amp;lt; 10%)','train_id': 5},
# '11300': {'class_name': 'Isolated Structures', 'train_id': 6},
# '12100': {'class_name': 'Industrial, commercial, public, military and private units','train_id': 7},
# '12210': {'class_name': 'Fast transit roads and associated land','train_id': 8},
# '12220': {'class_name': 'Other roads and associated land', 'train_id': 8},
# '12230': {'class_name': 'Railways and associated land', 'train_id': 10},
# '12300': {'class_name': 'Port areas', 'train_id': 11},
# '12400': {'class_name': 'Airports', 'train_id': 12},
# '13100': {'class_name': 'Mineral extraction and dump sites', 'train_id': 13},
# '13300': {'class_name': 'Construction sites', 'train_id': 14},
# '13400': {'class_name': 'Land without current use', 'train_id': 15},
# '14100': {'class_name': 'Green urban areas', 'train_id': 16},
# '14200': {'class_name': 'Sports and leisure facilities', 'train_id': 17},
# '21000': {'class_name': 'Arable land (annual crops)', 'train_id': 18},
# '22000': {'class_name': 'Permanent crops (vineyards, fruit trees, olive groves)','train_id': 19},
# '23000': {'class_name': 'Pastures', 'train_id': 20},
# '24000': {'class_name': 'Complex and mixed cultivation patterns','train_id': 21},
# '25000': {'class_name': 'Orchards at the fringe of urban classes','train_id': 22},
# '31000': {'class_name': 'Forests', 'train_id': 23},
# '32000': {'class_name': 'Herbaceous vegetation associations (natural grassland, moors...)','train_id': 24},
# '33000': {'class_name': 'Open spaces with little or no vegetations (beaches, dunes, bare rocks, glaciers)','train_id': 25},
# '40000': {'class_name': 'Wetland', 'train_id': 26},
# '50000': {'class_name': 'Water bodies', 'train_id': 27}
#}

class_dict = {
 '11100': {'class_name': 'Continuous Urban Fabric (S.L. &amp;gt; 80%)','train_id': 1},
 '11210': {'class_name': 'Discontinuous Dense Urban Fabric (S.L. : 50% - 80%)','train_id': 2},
 '11220': {'class_name': 'Discontinuous Medium Density Urban Fabric (S.L. : 30% - 50%)','train_id': 3},
 '11230': {'class_name': 'Discontinuous Low Density Urban Fabric (S.L. : 10% - 30%)','train_id': 4},
 '11240': {'class_name': 'Discontinuous Very Low Density Urban Fabric (S.L. &amp;lt; 10%)','train_id': 5},
 '11300': {'class_name': 'Isolated Structures', 'train_id': 6},
 '12100': {'class_name': 'Industrial, commercial, public, military and private units','train_id': 7},
 '12210': {'class_name': 'Fast transit roads and associated land','train_id': 8},
 '12220': {'class_name': 'Other roads and associated land', 'train_id': 8},
 '12230': {'class_name': 'Railways and associated land', 'train_id': 9},
 '12300': {'class_name': 'Port areas', 'train_id': 10},
 '12400': {'class_name': 'Airports', 'train_id': 11},
 '13100': {'class_name': 'Mineral extraction and dump sites', 'train_id': 12},
 '13300': {'class_name': 'Construction sites', 'train_id': 13},
 '13400': {'class_name': 'Land without current use', 'train_id': 14},
 '14100': {'class_name': 'Green urban areas', 'train_id': 15},
 '14200': {'class_name': 'Sports and leisure facilities', 'train_id': 16},
 '21000': {'class_name': 'Arable land (annual crops)', 'train_id': 17},
 '22000': {'class_name': 'Permanent crops (vineyards, fruit trees, olive groves)','train_id': 18},
 '23000': {'class_name': 'Pastures', 'train_id': 19},
 '24000': {'class_name': 'Complex and mixed cultivation patterns','train_id': 20},
 '25000': {'class_name': 'Orchards at the fringe of urban classes','train_id': 21},
 '31000': {'class_name': 'Forests', 'train_id': 22},
 '32000': {'class_name': 'Herbaceous vegetation associations (natural grassland, moors...)','train_id': 23},
 '33000': {'class_name': 'Open spaces with little or no vegetations (beaches, dunes, bare rocks, glaciers)','train_id': 24},
 '40000': {'class_name': 'Wetland', 'train_id': 25},
 '50000': {'class_name': 'Water bodies', 'train_id': 26}
}
